info:
  PROJECT_ID: kaggle-300711
  TRACKING_URI: http://34.74.197.236:5000
  TITLE: stacking18-ver4-smalllr
  EXPERIMENT_ID: '2'
  SHARE_DRIVE_PATH: /content/drive/Shareddrives/便利用/kaggle/cassava/output
tag:
  scheduler: CosineAnnealingWarmRestarts  # ['ReduceLROnPlateau', 'CosineAnnealingLR', 'CosineAnnealingWarmRestarts']
  criterion: bi_tempered_logistic_loss
  
cfg:
  debug: false
  apex: false
  print_freq: 100
  num_workers: 4
  size: 512
  epochs: 1000
  early_stopping_round: 30
  # factor: 0.2 # ReduceLROnPlateau
  # patience: 0 # ReduceLROnPlateau
  # eps: 1.0e-6 # ReduceLROnPlateau
  # T_max: 10 # CosineAnnealingLR
  T_0: 10 # CosineAnnealingWarmRestarts
  lr: 1.0e-3
  min_lr: 1.0e-5
  batch_size: 512
  weight_decay: 1.0e-6
  gradient_accumulation_steps: 1
  max_grad_norm: 1000
  bi_tempered_loss_t1: 0.2
  bi_tempered_loss_t2: 1.
  seed: 42
  target_size: 5
  target_col: label
  n_fold: 5
  trn_fold:
    - 0
    - 1
    - 2
    - 3
    - 4
  stage1_models:
    - 38
    - 39
    - 40
    - 41
    - 42
  # train: true
  # inference: false
